---
title: Bird watch website 2.0
hero_image: images/banner.png
description: Take your website design skills further!
theme: navy
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3.0.0
last_tested: '2018-04-06'
steps:
- title: Step 1
- title: Step 2
- title: Step 3
  completion:
  - engaged
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
- title: Step 8
- title: Step 9
- title: Step 10
  completion:
  - internal
- title: Step 11
  completion:
  - external
