---
title: Bird watch website 2.0
hero_image: images/banner.png
description: Take your website design skills further!
theme: navy
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3.0.0
last_tested: '2018-04-06'
landing: true
steps:
  - title: Choose colours with hex codes
  - title: Use CSS on sections
    completion:
      - engaged
  - title: Create a reusable text box
  - title: Reusable the text box
  - title: Style paragraph text
  - title: Give the home page a unique id
  - title: Style the image
  - title: Animate parts of your site
  - title: Add hover effects
    completion:
      - internal
  - title: "Challenge: glowing links"
    completion:
      - external
  - title: More challenges
    challenge: true
